import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" data-theme="light">
          <body className="min-h-screen flex flex-col">
              <AuthProvider>
                  <Navbar />
                  <main className="flex-1">
                      {children}
                  </main>
                  <Footer />
              </AuthProvider>
          </body>
      </html>
  );
}
